[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"
publish = false

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.dependencies]
edged-core = { path = "crates/edged-core" }
edged-macos = { path = "crates/edged-macos" }
inset = "0.3.0"
inset-animation = "0.3.0"
inset-embedder-winit = "0.3.0"
inset-foundation = "0.3.0"
inset-rendering = "0.3.0"
inset-winui = { path = "../inset-winui/crates/inset-winui" }
valo-codec-apple = "0.5.0"
block2 = "0.6"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-application-services = "0.3"
objc2-core-foundation = "0.3"
objc2-core-graphics = "0.3"
objc2-foundation = "0.3"
objc2-quartz-core = "0.3"
raw-window-handle = "0.6"
objc2-service-management = "0.3"
objc2-screen-capture-kit = "0.3"
objc2-core-media = "0.3"
objc2-core-video = "0.3"
